#!/bin/bash

TMPDIR=$(mktemp -d)

mkdir ${TMPDIR}/lib
mkdir ${TMPDIR}/img
mkdir ${TMPDIR}/doc

cp lib/*.py ${TMPDIR}/lib
cp img/*.png ${TMPDIR}/img
cp doc/*.txt ${TMPDIR}/doc
cp sshgui.py ${TMPDIR}
cp appimage.d/AppRun ${TMPDIR}
cp appimage.d/sshgui.desktop ${TMPDIR}
cp appimage.d/sshgui.png ${TMPDIR}
ln -sf sshgui.png ${TMPDIR}/.DirIcon

ARCH=x86_64 appimagetool-x86_64.AppImage ${TMPDIR} sshgui.appImage

rm -rf ${TMPDIR}

