#!/bin/bash

TMPDIR=$(mktemp -d)
APPIMGTOOL=/opt/appimagetool-x86_64.AppImage
VERSION=1.2


mkdir ${TMPDIR}/lib
mkdir ${TMPDIR}/img
mkdir ${TMPDIR}/doc

cp lib/*.py ${TMPDIR}/lib
cp img/*.png ${TMPDIR}/img
cp doc/*.txt ${TMPDIR}/doc
cp sshgui.py ${TMPDIR}
cp appimage.d/AppRun ${TMPDIR}
cp appimage.d/sshgui.desktop ${TMPDIR}
cp appimage.d/sshgui.png ${TMPDIR}
ln -sf sshgui.png ${TMPDIR}/.DirIcon

ARCH=x86_64 ${APPIMGTOOL} ${TMPDIR} sshgui-${VERSION}.appImage

rm -rf ${TMPDIR}

